name: Build

on: [push, pull_request]

jobs:
  msvc:
    strategy:
      matrix:
        arch: [x64, arm64]

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.arch }}-windows
      BUILD_CONFIGURATION: Release

    runs-on: windows-2025
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: lukka/get-cmake@9e07ecdcee1b12e5037e42f410b67f03e2f626e1 # v4.2.1
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
      with:
        vcpkgGitCommitId: d1ff36c6520ee43f1a656c03cd6425c2974a449e
        vcpkgJsonGlob: '**/windows/vcpkg.json'

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
      if: ${{ matrix.arch != 'arm64' }}
      with:
        configurePreset: win-${{ matrix.arch }}-release
        buildPreset: win-${{ matrix.arch }}-release
        testPreset: win-${{ matrix.arch }}-release

    - name: Run CMake with vcpkg.json manifest (NO TESTS)
      uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
      if: ${{ matrix.arch == 'arm64' }}
      with:
        configurePreset: win-${{ matrix.arch }}-release
        buildPreset: win-${{ matrix.arch }}-release

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: backend-build-win-${{matrix.arch}}
        path: |
            ${{ github.workspace }}/build/**/Release/ovpnagent.exe
            ${{ github.workspace }}/build/**/Release/omicliagent.exe
            ${{ github.workspace }}/build/**/omi/Release/*.dll
            ${{ github.workspace }}/build/**/ovpnagent/win/Release/*.dll

