name: Mac Build

on: [workflow_dispatch]

jobs:
  mac:
    strategy:
      matrix:
        include:
          - name: macOS-arm64-14
            runner: macos-14
            arch: arm64
          - name: macOS-arm64-15
            runner: macos-15
            arch: arm64
          - name: macOS-arm64-26
            runner: macos-26
            arch: arm64
          - name: macOS-amd64-15
            runner: macos-15-intel
            arch: amd64
            

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install asio cmake fmt jsoncpp lz4 openssl pkg-config xxhash dylibbundler
          
      - name: Configure build
        run: |
          mkdir build
          cd build

          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            OPENSSL_ROOT="/opt/homebrew/opt/openssl"
            PREFIX_PATH="/opt/homebrew"
          else
            OPENSSL_ROOT="/usr/local/opt/openssl"
            PREFIX_PATH="/usr/local/opt"
          fi
          cmake -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT -DCMAKE_PREFIX_PATH=$PREFIX_PATH ..

      - name: Build
        run: |
          cd build
          cmake --build .
      
      - name: Bundle dylibs
        run: |
          mkdir -p artifact/omicliagent/lib
          mkdir -p artifact/agent/lib
      
          dylibbundler -od -b \
            -x build/openvpn/omi/omicliagent \
            -d artifact/omicliagent/lib
      
          dylibbundler -od -b \
            -x build/openvpn/ovpnagent/mac/agent_macos \
            -d artifact/agent/lib
                
      - name: Collect artifacts
        run: |
          cp build/openvpn/omi/omicliagent artifact/omicliagent/
          cp build/openvpn/ovpnagent/mac/agent_macos artifact/agent/

      - name: Create tarball
        run: |
          tar -cvf backend-build-${{ matrix.name }}.tar -C artifact .

      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ matrix.name }}
          path: backend-build-${{ matrix.name }}.tar
