name: Windows Build

on: [workflow_dispatch]

jobs:
  msvc:
    strategy:
      matrix:
        arch: [x64, arm64]

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.arch }}-windows
      BUILD_CONFIGURATION: Release

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7
    - uses: lukka/get-cmake@v4.3.3 
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v11.6 
      with:
        vcpkgJsonGlob: '**/windows/vcpkg.json'

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10.9
      if: ${{ matrix.arch != 'arm64' }}
      with:
        configurePreset: win-${{ matrix.arch }}-release
        buildPreset: win-${{ matrix.arch }}-release
        testPreset: win-${{ matrix.arch }}-release

    - name: Run CMake with vcpkg.json manifest (NO TESTS)
      uses: lukka/run-cmake@v10.9 
      if: ${{ matrix.arch == 'arm64' }}
      with:
        configurePreset: win-${{ matrix.arch }}-release
        buildPreset: win-${{ matrix.arch }}-release
            
    - name: Collect selected binaries into single folder
      shell: powershell
      run: |
        $out = "${{ github.workspace }}\staging\${{ matrix.arch }}"
        New-Item -ItemType Directory -Force -Path $out
    
        Get-ChildItem "${{ github.workspace }}\build" -Recurse |
          Where-Object {
            $_.FullName -like "*\Release\iitdvpnagent.exe" -or
            $_.FullName -like "*\Release\iitdvpncli.exe" -or
            $_.FullName -like "*\omi\Release\*.dll" -or
            $_.FullName -like "*\ovpnagent\win\Release\*.dll"
          } |
          Copy-Item -Destination $out -Force
    
        Get-ChildItem $out
        
    - name: Upload backend binaries
      uses: actions/upload-artifact@v7
      with:
        name: iitdvpn-backend-win-${{ matrix.arch }}
        path: | 
                ${{ github.workspace }}\staging\${{ matrix.arch }}\
